In [1]:
import numpy as np

In [9]:
arr_4d = np.arange(0,81).reshape((3,3,3,3))

In [10]:
arr_4d

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [12]:
arr_3d[1:, 0:1, 1:2, 1:3]

array([[[[31, 32]]],


       [[[58, 59]]]])

In [2]:
arr = np.arange(21,26)

In [3]:
print(arr)

[21 22 23 24 25]


In [4]:
arr[3]

24

In [5]:
arr[-2]

24

In [8]:
arr = np.arange(0,10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
arr[2, 1]

5

In [10]:
arr[4, 0]

8

In [15]:
arr = np.arange(45,60)

In [35]:
len(arr)

15

In [36]:
ind = np.array([[3, 2],[5, 14]])

In [37]:
ind

array([[ 3,  2],
       [ 5, 14]])

In [39]:
print(arr[14])

59


In [38]:
arr[ind]

array([[48, 47],
       [50, 59]])

In [40]:
list_example = [3, 4, 1, 10, 12, 5, 6, 8]

In [43]:
list_example[1:]

[4, 1, 10, 12, 5, 6, 8]

In [44]:
arr = np.arange(20,50)

In [45]:
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [57]:
arr_slice = slice(3, 24, 2)

In [58]:
arr[arr_slice]

array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43])

In [52]:
arr[3:24]

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43])

In [53]:
arr[:24]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43])

In [56]:
arr[3:]

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [60]:
arr[3:24:2]

array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43])

In [77]:
arr2d = np.arange(0,9).reshape((3,3))

In [78]:
arr3d = np.arange(0,27).reshape((3,3,3))

In [69]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
arr2d[1:3, 1:3]

array([[4, 5],
       [7, 8]])

In [84]:
for i in range(3):
    for j in range(3):
        print(arr2d[i, j])
#         for k in range(3):
#             print(i, j, k)
#         print(arr2d[i, j])

0
1
2
3
4
5
6
7
8


In [79]:
for element in np.nditer(arr3d):
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [93]:
arr = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [94]:
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [95]:
arr.shape

(2, 4)

In [97]:
np.reshape(arr, (4, 2))

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

In [2]:
a = np.array([[1,2],[3,4]])
print(a)
a.shape

[[1 2]
 [3 4]]


(2, 2)

In [3]:
b = np.array([[5, 6]])
print(b)
b.shape

[[5 6]]


(1, 2)

In [105]:
print(b)
print(b.T)

[[5 6]]
[[5]
 [6]]


In [106]:
print(a) # 2 x 2
print(b) # 1 X 2 ( 2 x 1)

[[1 2]
 [3 4]]


In [4]:
# axis = 1
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [123]:
a = np.array([10, 20, 30, 40])
b = np.array([25, 35, 45, 55])
d = np.array([1, 11, 21, 31])
c = np.array([33, 44, 55, 66])

In [124]:
np.stack((a, b,d, c))

array([[10, 20, 30, 40],
       [25, 35, 45, 55],
       [ 1, 11, 21, 31],
       [33, 44, 55, 66]])

In [122]:
np.column_stack((a, b, c))

array([[10, 25, 33],
       [20, 35, 44],
       [30, 45, 55],
       [40, 55, 66]])

In [125]:
a = np.array([[1, 2, 3], [4, 5 ,6]])
print(a)
b = np.array([[10, 20 , 30], [40, 50, 60]])
print(b)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In [126]:
np.hstack((a, b))

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [127]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [128]:
a = np.arange(16).reshape((4, 4))

In [129]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [130]:
np.save('a.npy',a)

In [131]:
b = np.load('a.npy')
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
np.savetxt('a_csv.csv', a, delimiter = ',')

In [139]:
b = np.genfromtxt('a_csv.csv', delimiter = ',',dtype=int)

In [140]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
list_1 = ['house','hotel','home','table','robert','hook']

In [6]:
filter_list = list(filter(lambda a:a.startswith('ho'), list_1))

In [7]:
filter_list

['house', 'hotel', 'home', 'hook']

In [17]:
input_from_user = input("Give an integer")

result = 0
try:
    result = int(input_from_user) + 4
    print(a)
except ValueError:
#     print(str(e))
    print(f"It's a value error")
except NameError:
    print("It's a name error")
except:
    print("It's an exception")

Give an integercverver
It's a value error


In [6]:
# Some code
print(result)

0
