In [4]:
import numpy as np

np.set_printoptions(formatter={'fplot_kind':'{:.3f}'.format})  # Seted a o/p float range upto 3 decimal 


In [5]:
# Now to create array for 1000 movie ids starting from 1301
movie_id=np.arange(1301,2301)
print(movie_id[:5])
movie_id.size

[1301 1302 1303 1304 1305]


1000

In [6]:
# To create an array for 100 user ids between 20201 to 20301

user_id= np.arange(20201,20301)
print(user_id[:5])
user_id.size
user_id

[20201 20202 20203 20204 20205]


array([20201, 20202, 20203, 20204, 20205, 20206, 20207, 20208, 20209,
       20210, 20211, 20212, 20213, 20214, 20215, 20216, 20217, 20218,
       20219, 20220, 20221, 20222, 20223, 20224, 20225, 20226, 20227,
       20228, 20229, 20230, 20231, 20232, 20233, 20234, 20235, 20236,
       20237, 20238, 20239, 20240, 20241, 20242, 20243, 20244, 20245,
       20246, 20247, 20248, 20249, 20250, 20251, 20252, 20253, 20254,
       20255, 20256, 20257, 20258, 20259, 20260, 20261, 20262, 20263,
       20264, 20265, 20266, 20267, 20268, 20269, 20270, 20271, 20272,
       20273, 20274, 20275, 20276, 20277, 20278, 20279, 20280, 20281,
       20282, 20283, 20284, 20285, 20286, 20287, 20288, 20289, 20290,
       20291, 20292, 20293, 20294, 20295, 20296, 20297, 20298, 20299,
       20300])

In [ ]:
# or we can create user ids as below also 

user_id=[]
for i in range(20201,20301):
    user_id.append(i)
user_id=np.array(user_id)
user_id

In [7]:
# now to create movie matrix: 
import random
movie_matrix = []

for user in range(100):
    movies_rated_by_me = np.full(1000,-1)
    num_of_movies_rated = random.randint(0,999) # Choosing randomly how many movies are rated 
    movies_that_i_will_rate = random.sample(range(0,1000),num_of_movies_rated) # It will create index between 0 to 1000 randomly and will assign it to all the 10000 movies for which the user has been rated 

    for index in movies_that_i_will_rate:
        movies_rated_by_me[index] = random.randint(0,10)
    movie_matrix.append(movies_rated_by_me)
   
movie_matrix = np.array(movie_matrix)

In [8]:
# To print the specifications of movie matrix 
print("Shape of the matrix:", movie_matrix.shape)
print("Number of elements in the array: ",movie_matrix.size)
print("Number of dimension in array: ", movie_matrix.ndim)

Shape of the matrix: (100, 1000)
Number of elements in the array:  100000
Number of dimension in array:  2


In [9]:
# Task3: To add the 10 expert movie ratings

import random

expert_matrix = []
for user in range(10):
    movies_rated_by_me = np.full(1000,-1)
    num_of_movies_rated = random.randint(0,999)
    movies_that_i_will_rate = random.sample(range(0,1000),num_of_movies_rated)

    for index in movies_that_i_will_rate:
        movies_rated_by_me[index] = random.randint(0,10)
    expert_matrix.append(movies_rated_by_me)
expert_matrix = np.array(expert_matrix)

In [10]:
print("Shape of the matrix:", expert_matrix.shape)
print("Number of elements in the array: ",expert_matrix.size)
print("Number of dimension in array: ", expert_matrix.ndim)

Shape of the matrix: (10, 1000)
Number of elements in the array:  10000
Number of dimension in array:  2


In [11]:
# To add the expert reviews to the original reviews 

movie_matrix = np.vstack([movie_matrix, expert_matrix])
movie_matrix.shape

(110, 1000)

In [13]:
# Now to add the 50 more movies to the existing matrx:

new_movie_matrix = []
for user in range(110):
    movies_rated_by_me = np.full(50,-1)
    num_movies_rated = random.randint(0,49)
    movies_that_i_will_rate = random.sample(range(0,50),num_movies_rated)

    for index in movies_that_i_will_rate:
        movies_rated_by_me[index] = random.randint(0,10)
    new_movie_matrix.append(movies_rated_by_me)
    
new_movie_matrix = np.array(new_movie_matrix)
print(new_movie_matrix.shape)


(110, 50)


In [14]:
print("Shape of the matrix:", new_movie_matrix.shape)
print("Number of elements in the array: ",new_movie_matrix.size)
print("Number of dimension in array: ", new_movie_matrix.ndim)

Shape of the matrix: (110, 50)
Number of elements in the array:  5500
Number of dimension in array:  2


In [15]:
# To append the movie ids :

new_movie_id = np.append(movie_id,np.arange(2301,2351))
new_movie_id.size

1050

In [78]:
movie_matrix = np.hstack([movie_matrix,new_movie_matrix])
movie_matrix.shape

(110, 1700)

In [18]:
# To get the final movie rating:

final_movie_rating = []
for i in range(1050):
    m = movie_matrix[:,i]
    m=m[m>=0]
    total_num_rating = m.size
    rating = m.mean()
    standard_deviation = m.std()
    final_movie_rating.append([new_movie_id[i],rating,total_num_rating,standard_deviation])


IndexError: index 1000 is out of bounds for axis 1 with size 1000

In [19]:
final_movie_rating = np.array(final_movie_rating)
final_movie_rating.size

4000

In [85]:
print(final_movie_rating[:,1].min())
print(final_movie_rating[:,1].max())

3.673076923076923
6.280701754385965


In [17]:
#  Converting the averagr of movie rating to get the range between 0 to 10 

x = final_movie_rating[:,1]
old_range = x.max() - x.min()
new_range = (10 - 0)
final_movie_rating[:,1]= ((x - x.min())*(new_range/old_range) + 0)

final_movie_rating 

TypeError: list indices must be integers or slices, not tuple

In [1]:
final_movie_rating .shape

NameError: name 'final_movie_rating' is not defined