In [ ]:
# Array Manipulation & File Handling: 
"""
# TOPICS:
    -> Indexing 
    -> Fancy indexing 
    -> Slicing 
    -> Iterating numpy array 
    -> Array Manipulation 
    -> File handling using Numpy 
    -> Numpy case study - Movie rating Syatem 
     
Array indexcing use square bracket '[]' to index the element of array so that the element can be reffered individually for various use case.

When we create an array an appropriate array index is also created for the same.
0  1 2 3 4-->
[9,8,7,6,5]
-5-4-3-2-1 <--


"""

In [3]:
# Examples: Indexing in single dimension array.

import numpy as np 
arr= np.arange(21,26)
print(arr)
element= arr[3]
print(element)

ele= arr[-4]
print(ele)

[21 22 23 24 25]
24
22


In [6]:
# Indexing in two dimensional array: In two dimensional array indexing the first index indicate row and second index indicate the colomn.

import numpy as np 
a1=np.arange(21,30).reshape(3,3)
print(a1)
ele=a1[2,2]
ele

[[21 22 23]
 [24 25 26]
 [27 28 29]]


29

In [9]:
# Fancy indexing: Fancy indexing means passing asn array of indices to access the multiple array at ehe same time.
    #This allow us to access and modify the complicated subset of the array.

import numpy as np 
a2=np.array([12,32,23,11,54,65,76,98])
print(a2)
ind=np.array([[5,4],[2,3]])
print(a2[ind])
"""
By using fancy indexing the shape of the result reflects the shape of the index array rather than the array being indexed.
"""

[12 32 23 11 54 65 76 98]
[[65 54]
 [23 11]]


In [1]:
# Slicing in numpy array: The slicing is same like in the list but just a difference is here we are usign a word slicing and then providing the same start, stop and step index. And instead of semicolon we use comma.
# The slice index is constructed by using start stop and step index using slice()
import numpy as np
a1= np.arange(0,10)
print(a1)
a1_slice=slice(0,8,2)
print(a1[a1_slice])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6]


In [20]:
# Slicing using another way:  
import numpy as np
a1= np.arange(10)
print(a1)
print(a1[2:8:1])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]


In [31]:
# Slicing in 2D array: 

import numpy as np
arr2d=np.arange(0,9).reshape(3,3)
print(arr2d) 

# Now to get 4,5,7,8 as square matrix 

arr_slice=arr2d[1:3,1:3]    # 3 is provided because it wikk work like 3-1=2 row and the colomn.
print(arr_slice)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[4 5]
 [7 8]]


In [37]:
# Iterating in numpy array: 
"""
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.



"""
# To iterate on basic 1d array as follow it will go through the each element one by one
    # for now we are using the conventional for loop to do it 

import numpy as np 
arr= np.array([1,2,3,4,5,6,7,8])
for x in arr:
    print(x)

1
2
3
4
5
6
7
8


In [41]:
# Iterating over 2d array: For 2D array also first it will go through all the arrays and then iterate over the elements.

import numpy as np 
arr3= np.arange(0,4).reshape(2,2)
print(arr3)

for x in arr3:     # x= number of ad array in arr3
    for y in x:     # y= number of elements in 1d array of arr3
        print(y)

"""
If we iterate on a n-D array it will go through n-1th dimension one by one.

To return the actual values, the scalars, we have to iterate the arrays in each dimension.
"""

[[0 1]
 [2 3]]
0
1
2
3


In [2]:
# Iterating over 3d array:

import numpy as np 
arr3=np.arange(0,27).reshape(3,3,3)


for x in arr3:
    for y in x:
        for z in y:
            print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
# Now to use the special function in numpy for iteration. i.e. np.nditer()
"""
The function nditer() is a helping function that can be used from very basic to very advanced iterations. 
It solves some basic issues which we face in iteration, lets go through it with examples.

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be 
difficult to write for arrays with very high dimensionality.
"""

import numpy as np 
arr3= np.arange(0,27).reshape(3,3,3)
arr3

for x in np.nditer(arr3):
    print(x)

In [59]:
# Iterating numpy array with different data type:
"""
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other 
space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].


"""
import numpy as np
arr= np.arange(4)

for x in np.nditer(arr, flags=['buffered'],op_dtypes=['S']):
    print(x)


b'0'
b'1'
b'2'
b'3'


In [6]:
# Enumerated iteration: Eumeration means mentioning sequence number of somethings one by one.

import numpy as np 
arr=np.arange(3)
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 0
(1,) 1
(2,) 2


In [9]:
# Array manipulation in numpy: To reshape or to create an array by using the already created array we use array manipulation.

#1. np.reshape(): To reshape the already existing array.

import numpy as np

arr= np.array([[1,2,3],[2,3,4]])
print(arr)

arr1= np.reshape(arr,(3,2))
arr1



[[1 2 3]
 [2 3 4]]


array([[1, 2],
       [3, 2],
       [3, 4]])

In [13]:
#2. ravel(): This function is used to convert already existing 2D or 3D array to 1D array.

import numpy as np 
a= np.arange(0,9).reshape(3,3)
print("Original array is: ",a)
b=np.ravel(a)   # providing 1d array out of 3d array.
print(b)

Original array is:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [17]:
#3. Transpose like operation: Transpose is used to invert row with colomn.

import numpy as np 
a = np.arange(0,9).reshape(3,3)
print("a Before transpose: ",a)
b= np.transpose(a)
print("a adter transpose: ",b)

a Before transpose:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
a adter transpose:  [[0 3 6]
 [1 4 7]
 [2 5 8]]


In [45]:
#4. Joining of array- comcatenate()/stack() : Multiple arrays are merged togather to get the new array that contain all the elements of arrays.
    #Syntex: numpy.concatenate((array1, array2, ...), axis=0)

# Method-1 : Using np.concatenate() function

import numpy as np 
a= np.arange(4).reshape(2,2)
print(a)
b= np.array([[5,6]])
print(b)
c= np.concatenate((a,b))     # b.T is used because when axis=1 we are adding in colomn axis and when axis=0 we are adding in row.
                            # The default value of axis=0, but we can change the axis value to 1 or 0.
print(c)
print("--------------------------------------")


# If axis=0

arr1= np.array([[1,2,3],[4,5,6]])
arr2= np.array([[7,8,9],[0,8,7]])
print(arr1,arr2)

print("---------------------------------------")

arr3= np.concatenate((arr1,arr2),axis=0)   # When axis=0 it will add in rows only 
print(arr3)

print("---------------------------------------")

# If axis=1

arr3= np.array([[9,8,7],[6,5,4]])
arr4= np.array([[43,56,]])

print(arr3,arr4.T)
print("---------------------------------------")
arr5= np.concatenate((arr3,arr4.T),axis=1)
print(arr5)

[[0 1]
 [2 3]]
[[5 6]]
[[0 1]
 [2 3]
 [5 6]]
--------------------------------------
[[1 2 3]
 [4 5 6]] [[7 8 9]
 [0 8 7]]
---------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 8 7]]
---------------------------------------
[[9 8 7]
 [6 5 4]] [[43]
 [56]]
---------------------------------------
[[ 9  8  7 43]
 [ 6  5  4 56]]


In [3]:
# Method-2 Using np.stack() function:  When we are using stack() function the size of array should be same.

    # Syntex: numpy.stack(arrays, axis=0)

import numpy as np 
a= np.arange(4).reshape(2,2)
b= np.array([[7,8],[0,8]])
print(a,'\n',b)
print("--------------------------")

c= np.stack((a,b),axis=1)
print(c)
print("--------------------------------")

    # Now to stack 1D array into an 2D or 3D array 

[[0 1]
 [2 3]] 
 [[7 8]
 [0 8]]
--------------------------
[[[0 1]
  [7 8]]

 [[2 3]
  [0 8]]]
--------------------------------


In [58]:
# Using colomn_stack() to convert 1D array to 2ED array: It will convert all 1D array into 2D array while it will put all the array into column.

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

d= np.column_stack((a,b,c))

print(d)



[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [65]:
# Use of hstack() and Vstack(): Its same like axis=0/1, 
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print(a)
b= np.array([[7,8,9],[98,89,9]])
print(b)
print("-------------------------")
c= np.hstack((a,b))      # It will add the second array as column to the first one.
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [98 89  9]]
-------------------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 98 89  9]]


In [70]:
import numpy as np 
a= np.array([[1,2,3],[4,5,6]])
print(a)
b= np.array([[98,65,34],[34,20,80]])

print(b)
print("----------------------")

c= np.vstack((a,b))    #    It will add another array as row to the first array.
print(c)

[[1 2 3]
 [4 5 6]]
[[98 65 34]
 [34 20 80]]
----------------------
[[ 1  2  3]
 [ 4  5  6]
 [98 65 34]
 [34 20 80]]


In [5]:
# Spliting of array: Spliting two arrays into two parts  

#1. Split(): It will split one combined array into multiple sub-arrays.

import numpy as np 
a=np.arange(16).reshape(4,4)
print(a)
[b,c,d,e]=np.split(a,4)
print([b,c,d,e])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [6]:
#2. hsplit(): It will split the array horizontaly.

import numpy as np 
a= np.arange(16).reshape(4,4)
print(a)
[b,c]=np.hsplit(a,2)
print("b=",b)
print("c=",c)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b= [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
c= [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [7]:
#3. vsplit(): It will split the array verticaly.
import numpy as np 
a= np.arange(16).reshape(4,4)
print(a)
[b,c]=np.vsplit(a,2)
print("b=",b)
print("c=",c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
b= [[0 1 2 3]
 [4 5 6 7]]
c= [[ 8  9 10 11]
 [12 13 14 15]]


In [18]:
# Storing and retriving the data: Numpy provides pair of function with the help of which we can save and retrive the data in binary format.
    # save(): To save the data or containt into binary format.
    # load(): To get back the data from binary to readable format. 
    # We use .npy, .npz extention.

import numpy as np
a=np.arange(16).reshape(4,4)
print(a)
print("----------------------------")

b=np.save('a.npy',a)   # Saved to bibnary 
print(b)
c=np.load('a.npy')  # Load back fron binary 
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------------
None
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [36]:
# Loading and retriving the data in text or CSV file : 
"""
Numpy provides two functions for that savetxt(), and genfromtxt() these two functions allows us to save and retrive the data in text file.

savetxt(): To save the data into text format 

genfromtxt(): To retrive the data from txt to general format.

save format are used for the CSV files also.


"""

import numpy as np 
a=np.arange(16).reshape(4,4)
print(a)

b=np.savetxt('a.txt',a,delimiter=',')
print(b)  # File containt is converted to Text format.


c= np.loadtxt('a.txt',delimiter=',')
print(c)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
None
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
