In [1]:
import numpy as np

In [2]:
# To print the versions of array
print(np.__version__)

1.23.1


In [3]:
def print_array_attribute(arr):
    """
    Function to print the attributes of array
    """
    print(f"The array is \n{arr}")
    print(f"\nThe shape of array is {arr.shape}")
    print(f"Dimension of array is {arr.ndim}")
    print(f"The size of array is {arr.size}")
    print(f"The data type of each element of array is {arr.dtype}")
    print(f"The byte size of each element of array is {arr.itemsize} bytes")

In [4]:
# List to create 1d array
a1d_list = [2, 3, 4, 5, 6,]

In [5]:
# 1d array creation with list
a1d_array = np.array(a1d_list)
a1d_array

array([2, 3, 4, 5, 6])

In [6]:
# Print attributes of array
print_array_attribute(a1d_array)

The array is 
[2 3 4 5 6]

The shape of array is (5,)
Dimension of array is 1
The size of array is 5
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [7]:
# List to create 2d array
a2d_list = [[1,2,3],[4,5,6],[7,8,9]]
a2d_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
# 2d array created using list
a2d_array = np.array(a2d_list)
a2d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Print attributes of array
print_array_attribute(a2d_array)

The array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The shape of array is (3, 3)
Dimension of array is 2
The size of array is 9
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [10]:
# List to create 3d array
a3d_list = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
a3d_list

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [11]:
# 3d array creation with list
a3d_array = np.array(a3d_list)
a3d_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
# Print attributes of array
print_array_attribute(a3d_array)

The array is 
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

The shape of array is (2, 3, 3)
Dimension of array is 3
The size of array is 18
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [13]:
# List to create 4d array
a4d_list = [[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]]
a4d_list

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
  [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]]

In [14]:
# 4d array creation with list
a4d_array = np.array(a4d_list)
a4d_array

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [15]:
# Print attributes of array
print_array_attribute(a4d_array)

The array is 
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]

The shape of array is (1, 3, 3, 3)
Dimension of array is 4
The size of array is 27
The data type of each element of array is int32
The byte size of each element of array is 4 bytes
