In [1]:
import numpy as np

In [2]:
# To print the versions of array
print(np.__version__)

1.23.1


In [3]:
def print_array_attribute(arr):
    """
    Function to print the attributes of array
    """
    print(f"The array is \n{arr}")
    print(f"\nThe shape of array is {arr.shape}")
    print(f"Dimension of array is {arr.ndim}")
    print(f"The size of array is {arr.size}")
    print(f"The data type of each element of array is {arr.dtype}")
    print(f"The byte size of each element of array is {arr.itemsize} bytes")

In [100]:
# Create an array from a dict
dic = {'a':1,'b':2}
arr_dic = np.array(dic)

In [103]:
arr_dic

numpy.ndarray

In [4]:
# List to create 1d array
a1d_list = [2, 3, 4, 5, 6,]

In [91]:
# 1d array creation with list
a1d_array = np.array(a1d_list)
a1d_array

array([2, 3, 4, 5, 6])

In [85]:
a1d_array = np.array((2, 3, 4, 5, 6,))
a1d_array

array([2, 3, 4, 5, 6])

In [86]:
print(a1d_array)

[2 3 4 5 6]


In [92]:
a1d_array_copy = a1d_array.copy()
print(a1d_array_copy)

[2 3 4 5 6]


In [98]:
a1d_array[4] = 10
a1d_array = np.append(a1d_array, 12)
print(a1d_array)

[ 2  3  4  5 10 12]


In [94]:
print(a1d_array_copy)

[2 3 4 5 6]


In [80]:
a1d_array[-4]

3

In [6]:
# Print attributes of array
print_array_attribute(a1d_array)

The array is 
[2 3 4 5 6]

The shape of array is (5,)
Dimension of array is 1
The size of array is 5
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [7]:
# List to create 2d array
a2d_list = [[1,2,3],[4,5,6],[7,8,9]]
a2d_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [81]:
# 2d array created using list
a2d_array = np.array(a2d_list)
a2d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a2d_array[-1, -2]

8

In [9]:
# Print attributes of array
print_array_attribute(a2d_array)

The array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The shape of array is (3, 3)
Dimension of array is 2
The size of array is 9
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [10]:
# List to create 3d array
a3d_list = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
a3d_list

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [11]:
# 3d array creation with list
a3d_array = np.array(a3d_list)
a3d_array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
# Print attributes of array
print_array_attribute(a3d_array)

The array is 
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

The shape of array is (2, 3, 3)
Dimension of array is 3
The size of array is 18
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [13]:
# List to create 4d array
a4d_list = [[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]]
a4d_list

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
  [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]]

In [14]:
# 4d array creation with list
a4d_array = np.array(a4d_list)
a4d_array

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [15]:
# Print attributes of array
print_array_attribute(a4d_array)

The array is 
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]

The shape of array is (1, 3, 3, 3)
Dimension of array is 4
The size of array is 27
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [44]:
a = np.arange(12).reshape(3,4)
# Print attributes of array
print_array_attribute(a)

The array is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

The shape of array is (3, 4)
Dimension of array is 2
The size of array is 12
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [45]:
b = np.arange(12).reshape(4,3)
# Print attributes of array
print_array_attribute(b)

The array is 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

The shape of array is (4, 3)
Dimension of array is 2
The size of array is 12
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [72]:
# Create an array with only zeroes
# Creating a 1D array
arr = np.zeros((10),dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [73]:
print_array_attribute(arr)

The array is 
[0 0 0 0 0 0 0 0 0 0]

The shape of array is (10,)
Dimension of array is 1
The size of array is 10
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [62]:
# Creating a 2D array
arr = np.zeros((4,6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [75]:
# Create an array with only ones
# Creating a 1D array
arr = np.ones((10),dtype=int)
print(arr)

[1 1 1 1 1 1 1 1 1 1]


In [77]:
arr[-2]

1

In [65]:
# Creating a 2D array
arr = np.ones((5,8))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [69]:
# Creating a 3D array
arr = np.ones((2,5,8))
print(arr)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [74]:
# Creating a 3D array
arr = np.ones((1,5,8))
print_array_attribute(arr)

The array is 
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]

The shape of array is (1, 5, 8)
Dimension of array is 3
The size of array is 40
The data type of each element of array is float64
The byte size of each element of array is 8 bytes


In [124]:
# Create an array of numpy using arange func
a1d_array_arange = np.arange(1,7)
a1d_array_arange

array([1, 2, 3, 4, 5, 6])

In [125]:
# Add 4 to each of the element in the array
a1d_array_arange + 4

array([ 5,  6,  7,  8,  9, 10])

In [126]:
# Multiply 4 to each of the element in the array
a1d_array_arange * 4

array([ 4,  8, 12, 16, 20, 24])

In [133]:
# Adding 2 arrays
first_array = np.arange(0,10)
second_array = np.ones(10)

In [134]:
print("first_array = ",first_array)
print("second_array = ",second_array)

first_array =  [0 1 2 3 4 5 6 7 8 9]
second_array =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [135]:
third_array = first_array + second_array
print("third_array = ",third_array)

third_array =  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [157]:
# Use case of reshape function
arr_1d = np.arange(0,10)
print_array_attribute(arr_1d)

The array is 
[0 1 2 3 4 5 6 7 8 9]

The shape of array is (10,)
Dimension of array is 1
The size of array is 10
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [159]:
arr_2d = arr_1d.reshape(2,5)
print_array_attribute(arr_2d)

The array is 
[[0 1 2 3 4]
 [5 6 7 8 9]]

The shape of array is (2, 5)
Dimension of array is 2
The size of array is 10
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [138]:
arr_3d = arr_1d.reshape(1,5,2)
print_array_attribute(arr_3d)

The array is 
[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]

The shape of array is (1, 5, 2)
Dimension of array is 3
The size of array is 10
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [139]:
arr_1d_reshaped = arr_2d.reshape(10)
print_array_attribute(arr_1d_reshaped)

The array is 
[0 1 2 3 4 5 6 7 8 9]

The shape of array is (10,)
Dimension of array is 1
The size of array is 10
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [152]:
first_array = np.arange(0,12).reshape(4,3)
second_array = np.ones((4,3),dtype=int)

In [153]:
print_array_attribute(first_array)

The array is 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

The shape of array is (4, 3)
Dimension of array is 2
The size of array is 12
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [154]:
print_array_attribute(second_array)

The array is 
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

The shape of array is (4, 3)
Dimension of array is 2
The size of array is 12
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [155]:
third_array = first_array + second_array

In [156]:
print_array_attribute(third_array)

The array is 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

The shape of array is (4, 3)
Dimension of array is 2
The size of array is 12
The data type of each element of array is int32
The byte size of each element of array is 4 bytes


In [2]:
# Create an array of numpy using linspace func
a1d_array_linspace = np.linspace(start = 5.5, stop = 10.5, num = 100)
# a1d_array_linspace

In [3]:
a1d_array_linspace

array([ 5.5       ,  5.55050505,  5.6010101 ,  5.65151515,  5.7020202 ,
        5.75252525,  5.8030303 ,  5.85353535,  5.9040404 ,  5.95454545,
        6.00505051,  6.05555556,  6.10606061,  6.15656566,  6.20707071,
        6.25757576,  6.30808081,  6.35858586,  6.40909091,  6.45959596,
        6.51010101,  6.56060606,  6.61111111,  6.66161616,  6.71212121,
        6.76262626,  6.81313131,  6.86363636,  6.91414141,  6.96464646,
        7.01515152,  7.06565657,  7.11616162,  7.16666667,  7.21717172,
        7.26767677,  7.31818182,  7.36868687,  7.41919192,  7.46969697,
        7.52020202,  7.57070707,  7.62121212,  7.67171717,  7.72222222,
        7.77272727,  7.82323232,  7.87373737,  7.92424242,  7.97474747,
        8.02525253,  8.07575758,  8.12626263,  8.17676768,  8.22727273,
        8.27777778,  8.32828283,  8.37878788,  8.42929293,  8.47979798,
        8.53030303,  8.58080808,  8.63131313,  8.68181818,  8.73232323,
        8.78282828,  8.83333333,  8.88383838,  8.93434343,  8.98

In [6]:
a1d_array_linspace[80] - a1d_array_linspace[79]

0.05050505050505194

In [7]:
a1d_array_linspace.size

100

In [54]:
def multiply_matrices(a,b):
    no_of_cols_a = a.shape[1]
    no_of_rows_b = b.shape[0]
    
    no_of_cols_b = b.shape[1]
    no_of_rows_a = a.shape[0]
    if no_of_cols_a == no_of_rows_b:
        c = np.dot(a,b)
        print(a)
        print("X")
        print(b)
        print("=")
        print(c)
    elif no_of_cols_b == no_of_rows_a:
        c = np.dot(b,a)
        print(b)
        print("X")
        print(a)
        print("=")
        print(c)
    else:
        print("The matrix cannot be multiplied")

In [58]:
multiply_matrices(b, a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
X
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
=
[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]]


In [8]:
np.array([6,5,8,2])

array([6, 5, 8, 2])

In [4]:
6 ** 2 + 4 ** 2

52

In [6]:
x = [np.log(-1), 1, np.log(0)]

C:\Users\Abhitesh.Debnath\AppData\Local\Temp\ipykernel_4844\3352044822.py:1: RuntimeWarning: invalid value encountered in log
  x = (np.log(-1),1, np.log(0))
C:\Users\Abhitesh.Debnath\AppData\Local\Temp\ipykernel_4844\3352044822.py:1: RuntimeWarning: divide by zero encountered in log
  x = (np.log(-1),1, np.log(0))


In [10]:
x

(nan, 1, -inf)

In [9]:
np.isnan(x)

array([ True, False, False])

In [11]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [12]:
x>1

array([False, False,  True,  True,  True])

In [13]:
x<4

array([ True,  True,  True,  True, False])

In [ ]:
True, True, True, True, True