In [ ]:
# Need of numpy array:
"""
By using numpy array we can perform complex mathematical operations like below
1. Creation of array/Matrices
2. To perform integral calculation
3. Solving differential equation
4. Statastic related operations

To perform such complex mathematical operations python does not contain any inbuilt library.
Numpy was written in python and C(Hence the performance of the numpy array is good as compared to conventional list) language also.
"""
# Why numpy is fast:
"""
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can 
access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with 
latest CPU architectures.
"""

# What is array in numpy :
"""
An array is a data structure which can store data of same data type.
In python this is the only difference between the list and the array because list can contain data 
corresponds to diffrent datatypes while array only have of same data type.
In numpy we can hold the data by using the array data structure.
The array which are created by using numpy are called nd array.
nd array are used in most of the data science library like pandas, scikit learn etc.

"""


In [ ]:
import numpy as np  # NumPy is usually imported under the np alias.


In [4]:
print(np.__version__)  # To print thr


1.23.1


In [10]:
# Numpy creating array: 

"""NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function."""

# type(): This built-in Python function tells us the type of the object passed to it.
#  Like in above code it shows that arr is numpy.ndarray type.

import numpy as np

lst = [1, 2, 3, 4]
lst1 = [5, 6, 7, 8]
lst2 = [9, 0, 1, 2]
arr = np.array([lst, lst1, lst2])
print(arr)
print(type(arr))
np.shape(arr)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]
<class 'numpy.ndarray'>


(3, 4)

In [3]:
# or we can directly pass the list/tuple/array
import numpy as np
arr1 = np.array((1, 2, 3, 4))
print(arr1)


[1 2 3 4]


In [20]:
# Function to print the array attribute:

def print_array_attributes(arr):  # Function to print Array atributes
    print(f"The array is \n{arr}")
    print(f"The shape of the array is {arr.shape}")
    print(f"The size of the array is {arr.size}")
    print(f"Array dimension is {arr.ndim}")
    print(f"Data type of an array is {arr.dtype}")
    print(f"The size of each element of array is {arr.itemsize} bytes")


In [16]:
print_array_attributes(arr2)


The array is 
[[1 2 3 4]
 [5 6 7 8]]
The shape of the array is (2, 4)
The size of the array is 8
Array dimension is 2
Data type of an array is int32
The size of each element of array is 4 bytes


In [4]:
# Higher dimensional array: To create an array with 5 Dimension.

import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print("Dmensions:", arr.ndim)


[[[[[1 2 3 4]]]]]
Dmensions: 5


In [6]:
# Array creation routines: Array can be created using the following methods.

# 1. Array of 1's and 0's : zeros() or ones() can create array of only ones or zeros with dimension given in the shape argument.

import numpy as np
arr = np.zeros((4, 5))
print('\n',arr)

arr1 = np.ones((5, 6))
print('\n',arr1)

# to change the data type of the element to int.
arr2 = np.ones((2), dtype=int)
print('\n',arr2)

# 3-D array of ons
aee3 = np.ones((2, 3, 4))
print('\n',aee3)



 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

 [1 1]

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [2]:
# 2. Creating an NUMPY array from the existing data:
import numpy as np
lst = [1, 2, 3, 4, 4]  # Existing data
arr = np.array(lst)
print(arr)


[1 2 3 4 4]


In [3]:
import numpy as np
lst = [1, 2, 3, 4]
a1 = np.array(lst)
print('\n',a1)

b1 = a1
print('\n',b1)
a1[1] = 9
print('\n',a1)    # Here means b1 is acting like poniter for the a1 and if we are changing any content of a1 the content
# of b1 is also changing because its stored at the same memeory location.
print('\n',b1)



 [1 2 3 4]

 [1 2 3 4]

 [1 9 3 4]

 [1 9 3 4]


In [4]:
# Hence we can use a .copy() function method  to avoide this.
import numpy as np
lst = [1, 2, 3, 4]
a1 = np.array(lst)
print(a1)
b1 = a1.copy()
print(b1)
a1[3] = 5
print(a1)
print(b1)    # now the copy array is not changed


[1 2 3 4]
[1 2 3 4]
[1 2 3 5]
[1 2 3 4]


In [40]:
# Create an numpy array using arange() fuhnction: In this method we can use starting, ending and step value
# and numpy will create an array in that range count.

import numpy as np
arr = np.arange(1, 20, 1)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
# also we can specify as below
import numpy as np
arr = np.arange(start=3, stop=24, step=1)
print(arr)


[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [58]:
# Creating an numpy array using linspace:

# syntex: numpy.linspace(start, stop, num=50)


import numpy as np
arr1 = np.linspace(start=2, stop=5, num=4)
print(arr1)


[2. 3. 4. 5.]


In [65]:
# Arithmatic operations on the numpy array: 
# 1. To add a number to the each element of the array.
import numpy as np 
lst= [1,2,3,4,5,6]
arr2=np.array(lst)
arr3=arr2+2
print(arr3)
arr4=arr2*2
print(arr4)
arr5=arr2/5
print(arr5)
arr6=arr2-6
print(arr6)


[3 4 5 6 7 8]
[ 2  4  6  8 10 12]
[0.2 0.4 0.6 0.8 1.  1.2]
[-5 -4 -3 -2 -1  0]


In [71]:
#2. How to add two arrays: To perform arithmatic operations on the two different arrays that array shoild be of same dimensions.

import numpy as np
arr1= np.array([1,2,3,4])
arr2= np.array([4,5,6,7])
print(arr1+arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1*arr2)


[ 5  7  9 11]
[-3 -3 -3 -3]
[0.25       0.4        0.5        0.57142857]
[ 4 10 18 28]


In [4]:
#  How to use reshape function: By using this function we can reshape the array to different dimensions.
import numpy as np 
arr1d= np.arange(0,12)
print_array_attributes(arr1d)

The array is 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
The shape of the array is (12,)
The size of the array is 12
Array dimension is 1
Data type of an array is int32
The size of each element of array is 4 bytes


In [5]:
arr2d=arr1d.reshape(4,3)    # This function is used to change the dimension of the aray or to reshaped the function.
print_array_attributes(arr2d)

The array is 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The shape of the array is (4, 3)
The size of the array is 12
Array dimension is 2
Data type of an array is int32
The size of each element of array is 4 bytes


In [9]:
import numpy as np 
arr1d= np.arange(0,16).reshape(4,4)
arr2= np.ones(16,dtype=int).reshape(4,4)
print_array_attributes(arr1d)
print_array_attributes(arr2)



The array is 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The shape of the array is (4, 4)
The size of the array is 16
Array dimension is 2
Data type of an array is int32
The size of each element of array is 4 bytes
The array is 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
The shape of the array is (4, 4)
The size of the array is 16
Array dimension is 2
Data type of an array is int32
The size of each element of array is 4 bytes


In [10]:
arradd=arr1d + arr2
print_array_attributes(arradd)

The array is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
The shape of the array is (4, 4)
The size of the array is 16
Array dimension is 2
Data type of an array is int32
The size of each element of array is 4 bytes


In [19]:
# To perform the matrix product: Syntex print(np.dot(a,b))

import numpy as np 
arr1= np.arange(0,9).reshape(3,3)
arr2= np.ones(9,dtype=int).reshape(3,3)
print(arr1)
print(arr2)

arr3=np.dot(arr1,arr2)
print(arr3)
print_array_attributes(arr3)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]
The array is 
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]
The shape of the array is (3, 3)
The size of the array is 9
Array dimension is 2
Data type of an array is int32
The size of each element of array is 4 bytes


In [8]:
 import numpy as np 
 arr= np.arange(0,9).reshape(3,3)
 print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
lst= [1,2,3,4,5,6,7,8,9]
arr2= np.array(lst).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import numpy as np 
arr3= np.dot(arr,arr2)

print(arr3)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]


In [1]:
# Function in numpy:  
"""Universal functions in Numpy are simple mathematical functions. Numpy provides various universal functions that cover a wide variety of operations. 
These functions include standard trigonometric functions, functions for arithmetic operations, handling complex numbers, statistical functions, etc.

    # Characteristics of universal functions:
        1. These functions are operates on ndarray.
        2. It performs elementwise fast nd operations.
        3. It supports various features like array brodcasting and type casting.
        4. Pyhton universal function can be created by using frompyfunc library function. 
        5. Some unifunc are used internally when any of the mathematical operator is being used in the operation.
            eg. When '+' operator is used in the statement then np.add() function is called internally. """

import numpy as np 
root=np.sqrt([4,9,81])
print(root)


[2. 3. 9.]


In [ ]:
# Types of universal functions:
""""
1. Mathematical operations
    add()
    log()
    sqrt()
    mod()
2. Trignometric function
    sin()
    cos()
    hypot()
3. Bit-twiddling fuhnction
    isinfinite()
    isnan()
4. Comparison function
    greater()
    less()
    equal()
5. Floating function
    bitwise_and()
    bitwise_or()
6. Aggregate function
    sum
    min
    max
    mean
    stnd deviation
"""

In [7]:
# 1. Mathematical function: Universal function performs a element wise operation on the array.

import numpy as np 
x= int(input("Enter the range of array: "))
a1= np.arange(x)
print("The array is :",a1)
a1_sum= a1.sum()
print("The total sum of the elements is:", a1_sum)




The array is : [0 1 2 3 4 5]
The total sum of the elements is: 15


In [34]:
import numpy as np
a= ([np.log(2),np.log(5)])
print(a)
np.isnan(a)  # It's checking is not a number.

[0.6931471805599453, 1.6094379124341003]


array([False, False])

In [14]:
# Trignometric funtions: These functions are only work on the radians, to perform these function we need to cover the angles to the radians by multi, it by pi/180.
"""
Functions                                      Description
--------------------------------------------------------------------------------------------------------
sin, cos tan   ------->                 It willperform the sin cos and the tan ioperation on the angles.
--------------------------------------------------------------------------------------------------------
arcsin,arccos,arctan    ------->        Calculate the inverse sin cosin and tangent. 
---------------------------------------------------------------------------------------------------------
hypot   ------->                        It will calculate the hypotnuse of the right triangle.
---------------------------------------------------------------------------------------------------------
sinh,cosh,tanh  ------->                It will perform the hyperbo;ic sin cos and tangent.
---------------------------------------------------------------------------------------------------------
arcsinh,atccosh,arctanh  ------->       To perform inverse hyperbolic sin cos and tangent.
---------------------------------------------------------------------------------------------------------
deg2rad ------->                        It will convert degree to radian.
---------------------------------------------------------------------------------------------------------
rad2deg ------->                        To convert rad to deg

"""
# Program to demostrate the trignometric functions:

import numpy as np 
Angles= np.array([24,45,67,89,87,54])
print_array_attributes(Angles)
print("-----------------------------------------------------")

Radians=np.deg2rad(Angles)      # Degree to radian conversion 
print_array_attributes(Radians)
print("-----------------------------------------------------")

sin_value=np.sin(Radians)
print_array_attributes(sin_value)
print("-----------------------------------------------------")

cos_value=np.cos(Radians)   # To print sin of the angles 
print_array_attributes(cos_value)



The array is 
[24 45 67 89 87 54]
The shape of the array is (6,)
The size of the array is 6
Array dimension is 1
Data type of an array is int32
The size of each element of array is 4 bytes
-----------------------------------------------------
The array is 
[0.41887902 0.78539816 1.1693706  1.55334303 1.51843645 0.9424778 ]
The shape of the array is (6,)
The size of the array is 6
Array dimension is 1
Data type of an array is float64
The size of each element of array is 8 bytes
-----------------------------------------------------
The array is 
[0.40673664 0.70710678 0.92050485 0.9998477  0.99862953 0.80901699]
The shape of the array is (6,)
The size of the array is 6
Array dimension is 1
Data type of an array is float64
The size of each element of array is 8 bytes
-----------------------------------------------------
The array is 
[0.91354546 0.70710678 0.39073113 0.01745241 0.05233596 0.58778525]
The shape of the array is (6,)
The size of the array is 6
Array dimension is 1
Data type 

In [15]:
cos_value=np.cos(Radians)       # To print the cos of angles
print_array_attributes(cos_value)           # And hence same goes for the others also 

The array is 
[0.91354546 0.70710678 0.39073113 0.01745241 0.05233596 0.58778525]
The shape of the array is (6,)
The size of the array is 6
Array dimension is 1
Data type of an array is float64
The size of each element of array is 8 bytes


In [19]:
# To calculate the hypotnuse and of the triangles:
import numpy as np
Base= int(input("Enter the Base of triangle: "))
Height= int(input("Enter the Height of triangle: "))
Hypotnuse=np.hypot(Base,Height)
print("Hypotnuse of the given angle is: ",Hypotnuse)

Hypotnuse of the given angle is:  4.242640687119285


In [18]:
# Statastical operatpion: These functions are used to calculate mean, median, variance, minimum of array elements. It includes functions like-
"""
Features                                                    Description
-----------------------------------------------------------------------------------------------------------------
1. amin,amax            ------->              Used to  find the minimum and the maximum of the given array 
------------------------------------------------------------------------------------------------------------------
2. ptp                  ------->              Used to find the range of the given array (minimum to maximum) 
------------------------------------------------------------------------------------------------------------------
3. percentile           ------->              Used to find the percentile of the given range of the array 
------------------------------------------------------------------------------------------------------------------
4. median               ------->              Calculate the median of the data along specific axis 
-------------------------------------------------------------------------------------------------------------------
5. mean                 ------->              Calculate the mean of the data along the given axis 
-------------------------------------------------------------------------------------------------------------------
6. std                  ------->              To calculate the standard deviation of the given array 
-------------------------------------------------------------------------------------------------------------------
7. var                  ------->              To calculate the variance of the data along the given axis    
-------------------------------------------------------------------------------------------------------------------
8. average              ------->              To calculate the average of the data along the given axis
             
"""

2.8284271247461903


In [14]:
# Demo:
import numpy as np 
weight= np.array([23,45,65,78,65,89])

min_weight=np.amin(weight )
print("Minimum weight of the student is:  ",min_weight)

max_weight=np.amax(weight)
print("Maximunm weight of the student is:  ",max_weight)

range_of_weight= np.ptp(weight)
print("Weight in the range of: ",range_of_weight)

median=np.median(weight) 
print("Median= ",median)

mean= np.mean(weight)
print("Mean= ",mean)

standard_devi= np.std(weight)
print("Standars deviation= ",standard_devi)

variance=np.var(weight)
print("Variance= ",variance)

average=np.average(weight)
print("Average= ",average)


Minimum weight of the student is:   23
Maximunm weight of the student is:   89
Weight in the range of:  66
Median=  65.0
Mean=  60.833333333333336
Standars deviation=  21.62110594355021
Variance=  467.47222222222223
Average=  60.833333333333336


In [ ]:
# Bit-twidlling operation: Python will take integer value as input it will convert it to binary number and perform the bitwise operations.

"""
Features                                        Description
----------------------------------------------------------------------------------------
bitwise_or      ------->          It will perform bitwise OR operation
----------------------------------------------------------------------------------------
bitwise_and     ------->          It will perform bitwise AND operation
----------------------------------------------------------------------------------------
bitwise_xor     ------->          It will perform bitwise XOR operation
----------------------------------------------------------------------------------------
invert          ------->          Will perform bitwise inversion of the array element 
----------------------------------------------------------------------------------------
left_shift      ------->          Perform the bitwise left shift of the array element 
----------------------------------------------------------------------------------------
right_shift     ------->           Perform the bitwise right shift of the array element  



"""


In [12]:
import numpy as np 
even = np.array([2,4,6,8,10,12])
odd= np.array([3,5,7,9,11,13])

print("AND_OP: ",np.bitwise_and(even,odd))

print("OR_OP: ",np.bitwise_or(even,odd))

print("Bitwise_XOR: ", np.bitwise_xor(even,odd))

print("Inversion:",np.invert(odd))

print("Right_shift: ",np.right_shift(even,1))

print("Left_shift: ",np.left_shift(even,1))

AND_OP:  [ 2  4  6  8 10 12]
OR_OP:  [ 3  5  7  9 11 13]
Bitwise_XOR:  [1 1 1 1 1 1]
Inversion: [ -4  -6  -8 -10 -12 -14]
Right_shift:  [1 2 3 4 5 6]
Left_shift:  [ 4  8 12 16 20 24]


In [26]:
#  Comparison function: greater(), less(), equal(), less_equal(), greater_equal()
import numpy as np
a1= np.array([2,3,4,5])
a2= np.array([5,6,7,8])
print("Greater: ",np.greater(a2,a1))

print("Less: ",np.less(a2,a1))

print("Greater: ",np.greater(a2,a1))

print("Less_or_equal:",np.less_equal(a1,a2))

print("Greater_or_equal: ",np.greater_equal(a1,a2))

Greater:  [ True  True  True  True]
Less:  [False False False False]
Greater:  [ True  True  True  True]
Less_or_equal: [ True  True  True  True]
Greater_or_equal:  [False False False False]


In [2]:
# Loadtxt: format:- numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None)
    # Used to load the data of any CSV file.

import numpy as np 
data= np.loadtxt('marks.csv',dtype=int,delimiter=',',usecols=(5),skiprows=1)
print(data)

[420 280 350 269 317 470 333 365 305 350 460 474 409 377 415 382 298 462
 370 313 464 302 252 259 308 392 424 403 370 328 398 434 291 472 263 439
 464 449 401 364 296 292 438 357 331 317 429 407 321 274 447 274 437 411
 257 310 396 270 311 459 378 316 283 266 381 409 313 306 448 348 292 400
 352 441 428 309 441 439 264 281 302 432 423 336 383 321 469 270 341 281
 403 333 323 348 345 397 449 261 456 370 322 379 446 404 301 254 351 444
 264 286 463 273 316 324 465 398 324 340 414 346 408 332 394 474 398 262
 410 391 444 461]


In [38]:


print("Minimum_marks: ",np.amin(data))

print("Maximum_marks: ",np.amax(data))

print("Standard_devi: ",np.std(data))

print("Average: ",np.average(data))

sum:  47356
Minimum_marks:  252
Maximum_marks:  474
Standard_devi:  66.17947803971762
Average:  364.2769230769231


In [3]:
# Logic functions: Testing truth value - all()
    # numpy.all() test whether all the element along the given axixs and check whether its evaluate to TRUE or not.

import numpy as np 
np.all([[True,False],[True,True]])   # it will perform aAND operation between two given arrays 
                                        #[True,False]= False
                                        #[True,True]= True
                                                    # False


                                        

False

In [5]:
import numpy as np 
np.all([[True,False],[True,True]],axis=0)

# This array is taken as: 
"""
[True     [True     ----> This will act as axis 0 = True


False ]     False]  ----> Will act as axis 1 = False 

"""                               # Hence the ans. ([True,False])

array([ True, False])

In [12]:
import numpy as np 
np.all([-1,5,1])






True

In [13]:
import numpy as np 
np.all([1,2,3,0])   #   For infinity also it will give true. Because its  not a zero.

#NaN positive infinity negative infinity  and evaluates to TRUE because its not equal to zero.

False

In [14]:
# Logic function testing truth value with - any() function 

    # numpy.any() test whether an array element along the axis of array evaluates to TRUE or not. It performs OR poeration 

import numpy as np 
np.any([[True,False],[False,True]])

True

In [16]:
import numpy as np 
np.any([[True,False],[False,False]],axis=0)  # Will do OR operation according to Axis.

array([ True, False])

In [18]:
import numpy as np 
np.any([-1,2,3])

True

In [21]:
# Logic function to test the array type: isreal or iscomplex

# np.copmlex()   Output will be TRUE if the given element are complex.conjugate
# np.real()      Output will be TRUE if the given element is real .

import numpy as np
j=1
np.iscomplex([2+3j,3,1+j,4,4+3j])

array([ True, False, False, False,  True])

In [23]:
import numpy as np 
j=1
np.isreal([2+4j,3,4,5])

array([False,  True,  True,  True])

In [44]:
# Element-wise logical operation: 
"""
 1. np.logical_and()
 2. np.logical_or()
 3. np.logical_xor()
 4. np.logical_not()
 5. np.greater()
 6. np.greater_equal()
 7. np.less()
 8. np.less_equal()
 9. np.equal()
 10. np.not_equal()

 And the output will be logical value TRUE/FALSE 

"""

import numpy as np 
x= np.arange(5)
print(x)
print(np.logical_and(x>1,x<4))

print(np.logical_or(x>1,x<4))

print(np.logical_not(x>1,x<4))

print(np.logical_xor(x>1,x<4))

print(np.greater([1,2,3,4,5],[6,9,4,23,2]))

print(np.greater_equal([3,4,5,6,7],[4,8,9,9,3]))

print(np.less([3,4,5,6,7],[9,7,6,8,9]))

print(np.less_equal([2,2,4,5],[1,2,3,4]))

print(np.equal([2,3,3,5],[1,2,3,4]))

print(np.not_equal([3,4,5,6],[9,6,5,4]))

[0 1 2 3 4]
[False False  True  True False]
[ True  True  True  True  True]
[ True  True False False False]
[ True  True False False  True]
[False False False False  True]
[False False False False  True]
[ True  True  True  True  True]
[False  True False False]
[False False  True False]
[ True  True False  True]


In [47]:
# Swapping row of the array:

import numpy as np 
A =np.arange(25).reshape(5,5)
print("Before swapping",A)
A[[0,1]]=A[[1,0]]
print("After swapping",A)

Before swapping [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After swapping [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [51]:
# Create 1-D array between 1-100 with 20 elements and evenly spaced 

import numpy as np
x=np.linspace(1,100,20)
print(x)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [62]:
# Create two random arrays and perform different operations on it:

import numpy as np 
A= np.random.randint(1,100,5)
B= np.random.randint(1,100,5)
print(A)
print(B)


print(np.equal(A,B))

print(np.greater(B,A))

print(np.isreal(A),np.isreal(B))

print(np.iscomplex(A),np.iscomplex(B))



[74 50 77 37 48]
[81 13 30  2 45]
[False False False False False]
[ True False False False False]
[ True  True  True  True  True] [ True  True  True  True  True]
[False False False False False] [False False False False False]
